name: pre-commit


on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:  # manually trigger the workflow

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: checkout the repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: upgrade pip
        run: python -m pip install --upgrade pip setuptools

      - name: install pre-commit
        run: |
          python -m pip install pre-commit

      - name: show versions
        run: |
          python -m pip list

      - name: install hooks
        run: |
          pre-commit install

      - name: autoupdate
        run: |
          pre-commit autoupdate
          # make sure to fail if something changed
          [ -z "$(git diff)" ] && false

      - name: open a PR if there were changes
        if: failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const date = new Date();
            const branch = "precommit-" + date.format("YYYYMMDD");

            await github.git.createRef({
              ref: `refs/heads/${branch}`,
              sha: context.sha,
              ...context.repo
            });
