on:
  push:
    tags:
      - 'v*'  # any version tag

name: upload release tarball

jobs:
  build:
    name: Upload Release Tarball
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pep517
      - name: build project
        run: |
          python -m pep517.build --source --binary .
      - name: set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Tarball
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing
          # it's ID to get its outputs object, which include a
          # `upload_url`. See this blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/test_project-$RELEASE_VERSION.tar.gz
          asset_name: test_project-$RELEASE_VERSION.tar.gz
          asset_content_type: application/gzip
