on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[skip-ci]') == false
    steps:
      - name: Test toJson
        run: |
          echo "${{ toJson(github.event.commits) }}"
