name: test CI
on:
  push:
    branches:
      - master

jobs:
  detect-ci-trigger:
    name: Detect CI Trigger
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      triggered: ${{ steps.detect_trigger.outputs.CI_TRIGGERED }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: detect trigger
        id: detect_trigger
        run: |
          git log -n 1 --pretty=format:%s ${{ github.ref }} | grep -q "\[skip-ci\]" \
          && echo '::set-output name=CI_TRIGGERED::true' \
          || echo '::set-output name=CI_TRIGGERED::false'

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: detect-ci-trigger
    if: github.event_name == 'push' && needs.detect-ci-trigger.outputs.triggered == 'false'
    steps:
      - name: Test toJson
        run: |
          echo "${{ toJson(github.event.commits) }}"
