name: test CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  detect-ci-trigger:
    name: Detect CI Trigger using a action
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    outputs:
      triggered: ${{ steps.detect-trigger.outputs.trigger-found }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/detect-ci-trigger
        id: detect-trigger
        with:
          keywords: "[test-upstream]"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: detect-ci-trigger
    if: |
      always()
      && github.repository == 'keewis/sphinx-test-project'
      && (
          (github.event_name == 'workflow_dispatch' || github.event_name == 'scheduled')
      )
    steps:
      - name: Test toJson
        run: |
          echo "${{ toJson(github.event.commits) }}"
